import { UserProvider } from "@auth0/nextjs-auth0/client"
import "./globals.css"
import 'leaflet/dist/leaflet.css';


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <UserProvider>
      <head>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
      </head>
      <body className="app-container">{children}</body>
      </UserProvider>
    </html>
  )
}